"use client"; 
import localFont from "next/font/local";
import "./globals.css";
import { useState, useEffect } from "react";
import React from 'react';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, isPopupOpen, confirmDeletePopup }) {

  const [showWelcomeMessage, setShowWelcomeMessage] = useState(false);
  const blurClass = isPopupOpen || confirmDeletePopup ? 'blur' : '';

  const [date, setDate] = useState('');
  
  useEffect(() => {
    const today = new Date();
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    setDate(today.toLocaleDateString(undefined, options));
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={blurClass}>

        <div className="logoContainer">
          <img src="/Logomark.png" alt="logo" className="logo"/>
          <h1>FocalPoint</h1>
        </div>

              {showWelcomeMessage && <h2 className="wellcomeMessage">Bem-vindo!</h2>}
      {React.Children.map(children, (child) => 
        React.cloneElement(child, { setShowWelcomeMessage })
      )}

        <div>
          <span>{date}</span>
        </div>
        </header>
        {children}
      </body>
    </html>
  );
}
