"use client"; 
import localFont from "next/font/local";
import "./globals.css";
import { useState, useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  const [date, setDate] = useState('');
  
  useEffect(() => {
    const today = new Date();
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    setDate(today.toLocaleDateString(undefined, options));
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>

        <div className="logoContainer">
          <img src="/Logomark.png" alt="logo" className="logo"/>
          <h1>FocalPoint</h1>
        </div>

        <h2 className="wellcomeMessage">Bem vindo de volta, Marcus</h2>

        <div>
          <span>{date}</span>
        </div>
        </header>
        {children}
      </body>
    </html>
  );
}
